# Generated by Django 6.0.6 on 2026-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data e hora do cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('tipo_maca', models.CharField(choices=[('GALA', 'Gala'), ('FUJI', 'Fuji'), ('EVA', 'Eva'), ('PINK_LADY', 'Pink Lady'), ('CRIPPS_PINK', 'Cripps Pink'), ('GRANNY_SMITH', 'Granny Smith'), ('RED_DELICIOUS', 'Red Delicious'), ('OUTRA', 'Outra')], max_length=20, verbose_name='tipo da maçã')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('GG', 'Extra grande')], max_length=2, verbose_name='tamanho da maçã')),
                ('quantidade_caixas', models.PositiveIntegerField(verbose_name='quantidade de caixas')),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='peso total (kg)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'carga',
                'verbose_name_plural': 'cargas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
