# Generated by Django 6.0.6 on 2026-07-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_carga_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='tipo_maca',
            field=models.CharField(choices=[('FUJI', 'Fuji'), ('GALA', 'Gala'), ('MISHIMA', 'Mishima'), ('GOLDEN', 'Golden'), ('OUTRA', 'Outra')], max_length=20, verbose_name='tipo da maçã'),
        ),
    ]
