# Generated by Django 6.0.6 on 2026-07-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_alter_carga_tipo_maca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='excluído em'),
        ),
    ]
