"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# DEBUG desligado por padrão: com ele desligado o Django usa as páginas de
# erro personalizadas (templates/404.html etc.) em vez das telas técnicas de
# depuração. Para desenvolver com as telas de erro detalhadas, rode com a
# variável de ambiente DJANGO_DEBUG=1 (ex.: $env:DJANGO_DEBUG='1' no PowerShell).
DEBUG = config("DEBUG", default=False, cast=bool)

# Com DEBUG desligado o Django só atende os hosts listados aqui.
# Para acessar pelo celular na mesma rede, adicione o IP do computador
# (ex.: '192.168.0.10') a esta lista.
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,[::1]",
    cast=Csv()
)
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# O Render injeta o hostname público automaticamente nesta variável:
RENDER_HOST = config("RENDER_EXTERNAL_HOSTNAME", default="")
if RENDER_HOST:
    ALLOWED_HOSTS.append(RENDER_HOST)
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_HOST}")

# Render encerra o HTTPS num proxy; isto faz o Django reconhecer a conexão
# como segura (necessário p/ login/CSRF funcionarem no site publicado):
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cargas',
    'contas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serve os arquivos estáticos (CSS do site e do admin) mesmo com
    # DEBUG desligado, sem precisar de um servidor web separado. Precisa vir
    # logo após o SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Redireciona para a troca de senha quem ainda está com senha provisória
    # (contas criadas por outro usuário). Ver contas/middleware.py.
    'contas.middleware.TrocaSenhaObrigatoriaMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Pasta de templates do projeto: guarda as páginas de erro (404.html,
        # 500.html etc.), que o Django procura pelo nome na raiz dos templates.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Pasta onde o `manage.py collectstatic` reúne todos os estáticos (do site e
# do admin) para o WhiteNoise servir. Não é versionada no Git — rode
# collectstatic em cada instalação (ver INSTALACAO.md).
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Autenticação
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

# Para onde o usuário não autenticado é redirecionado ao tentar acessar
# uma página protegida (as views usam LoginRequiredMixin).
LOGIN_URL = 'contas:entrar'
LOGIN_REDIRECT_URL = 'cargas:lista'
LOGOUT_REDIRECT_URL = 'contas:entrar'
